import localFont from "next/font/local";
import "./globals.css";
import { Koulen, Siemreap, Poppins } from "next/font/google";

import {
  FacebookIcon,
  Link,
  PhoneCall,
  Send,
  Youtube,
  YoutubeIcon,
} from "lucide-react";
import Image from "next/image";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });
const koulen = Koulen({ subsets: ["khmer"], weight: ["400"] });
const seimReap = Siemreap({ subsets: ["khmer"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-color2 ${geistSans.variable} ${geistMono.variable} antialiased ${poppins.className}`}
      >
        <section>
          <header>
            <nav className="bg-transparent border-gray-200 px-5 lg:px-10 py-2.5 dark:bg-gray-800">
              <div className="grid grid-cols-12 items-center max-w-screen-2xl mx-auto px-5 gap-4">
                {/* Search Section */}
                <div className="col-span-4">
                  <form className="w-full relative">
                    <label
                      htmlFor="default-search"
                      className="text-sm font-medium text-gray-900 sr-only dark:text-white"
                    >
                      Search
                    </label>
                    <div className="relative">
                      <div className="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                        <svg
                          className="w-4 h-4 text-gray-500 dark:text-gray-400"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 20 20"
                        >
                          <path
                            stroke="currentColor"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="M19 19l-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"
                          />
                        </svg>
                      </div>
                      <input
                        type="search"
                        id="default-search"
                        className="block w-full p-3 ps-10 text-sm text-gray-700 border border-gray-300 rounded-lg bg-gray-50 focus:ring-primary focus:border-primary dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400"
                        placeholder="Search Product..."
                        required
                      />
                      <button
                        type="submit"
                        className="text-white absolute end-1.5 bottom-1.5 bg-color font-medium rounded-lg text-sm px-4 py-2"
                      >
                        Search
                      </button>
                    </div>
                  </form>
                </div>
                {/* Logo Section */}
                <div className="col-span-4 flex justify-center items-center">
                  <Image
                    src="/assets/images/logo.png"
                    width={100}
                    height={100}
                    alt="Logo"
                  />
                </div>
                {/* Contact and Social Media Section */}
                <div className="col-span-4 flex justify-end space-x-4">
                  {/* Contact Info */}
                  <div className="bg-color2 p-2 flex items-center rounded-full px-4">
                    <PhoneCall className="h-4 mr-2" />
                    <span>800 123 45 78</span>
                  </div>
                  {/* Social Media Icons */}
                  <div className="flex items-center space-x-2">
                    {[
                      { Icon: FacebookIcon, href: "/client/news" },
                      { Icon: Send, href: "/client/news" },
                      { Icon: Youtube, href: "/client/news" },
                    ].map(({ Icon, href }, idx) => (
                      <a
                        key={idx}
                        href={href}
                        className="p-3 rounded-full bg-color hover:bg-color focus:ring-4 focus:ring-blue-300"
                        aria-label={`Social Media ${idx + 1}`}
                      >
                        <Icon className="w-6 h-6 text-white" />
                      </a>
                    ))}
                  </div>
                </div>
              </div>
            </nav>
          </header>
          <div className="flex justify-center p-4 bg-color-bold ">
            <div className="flex items-center lg:order-2">
              <button
                data-collapse-toggle="mobile-menu-2"
                type="button"
                className="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg lg:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                aria-controls="mobile-menu-2"
                aria-expanded="false"
              >
                <span className="sr-only">Open main menu</span>
                <svg
                  className="w-6 h-6"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    fill-rule="evenodd"
                    d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                    clip-rule="evenodd"
                  ></path>
                </svg>
                <svg
                  className="hidden w-6 h-6"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    fill-rule="evenodd"
                    d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                    clip-rule="evenodd"
                  ></path>
                </svg>
              </button>
            </div>
            <div
              className="hidden justify-between items-center w-full lg:flex lg:w-auto lg:order-1  "
              id="mobile-menu-2"
            >
              <ul
                className={`flex flex-col mt-4 font-medium lg:flex-row lg:space-x-8 lg:mt-0 ${koulen.className}`}
              >
                <li>
                  <a
                    href="/"
                    className="block py-2 pr-4 pl-3 text-white underline rounded bg-primary-700 lg:bg-transparent lg:text-primary-700 lg:p-0 dark:text-white"
                    aria-current="page"
                  >
                    ទំព័រដើម
                  </a>
                </li>
                <li>
                  <a
                    href="/client/news"
                    className="block py-2 pr-4 pl-3 text-white hover:underline border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700"
                  >
                    ព័ត៌មានថ្មីៗ
                  </a>
                </li>
                <li>
                  <a
                    href="/client/about"
                    className="block py-2 pr-4 pl-3 text-white hover:underline border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700"
                  >
                    អំពីវិទ្យាស្ថាន
                  </a>
                </li>
                <li>
                  <a
                    href="/client/news"
                    className="block py-2 pr-4 pl-3 text-white hover:underline border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700"
                  >
                    ប្រជុំរឿងព្រេងខ្មែរ
                  </a>
                </li>
                <li>
                  <a
                    href="/client/news"
                    className="block py-2 pr-4 pl-3 text-white hover:underline border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700"
                  >
                    បណ្ណាល័យ
                  </a>
                </li>
                <li>
                  <a
                    href="/client/news"
                    className="block py-2 pr-4 pl-3 text-white hover:underline border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700"
                  >
                    ទស្សនាវដ្ដីកម្ពុជសុរិយា
                  </a>
                </li>
                <li>
                  <a
                    href="/client/news"
                    className="block py-2 pr-4 pl-3 text-white hover:underline border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700"
                  >
                    នាទីព្រះពុទ្ធសាសនា
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </section>
        {children}
        <footer className="bg-color-bold  p-10">
          <ul
            className={`flex justify-center flex-col mt-4 font-medium lg:flex-row lg:space-x-8 lg:mt-0 ${koulen.className}`}
          >
            <li>
              <a
                href="/"
                className="block py-2 pr-4 pl-3 text-white underline  rounded bg-primary-700 lg:bg-transparent lg:text-primary-700 lg:p-0 dark:text-white"
                aria-current="page"
              >
                ទំព័រដើម
              </a>
            </li>
            <li>
              <a
                href="/client/news"
                className="block py-2 pr-4 pl-3 text-white hover:underline border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700"
              >
                ព័ត៌មានថ្មីៗ
              </a>
            </li>
            <li>
              <a
                href="/client/about"
                className="block py-2 pr-4 pl-3 text-white hover:underline border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700"
              >
                អំពីវិទ្យាស្ថាន
              </a>
            </li>
            <li>
              <a
                href="/client/news"
                className="block py-2 pr-4 pl-3 text-white hover:underline border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700"
              >
                ប្រជុំរឿងព្រេងខ្មែរ
              </a>
            </li>
            <li>
              <a
                href="/client/news"
                className="block py-2 pr-4 pl-3 text-white hover:underline border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700"
              >
                បណ្ណាល័យ
              </a>
            </li>
            <li>
              <a
                href="/client/news"
                className="block py-2 pr-4 pl-3 text-white hover:underline border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700"
              >
                ទស្សនាវដ្ដីកម្ពុជសុរិយា
              </a>
            </li>
            <li>
              <a
                href="/client/news"
                className="block py-2 pr-4 pl-3 text-white hover:underline border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700"
              >
                នាទីព្រះពុទ្ធសាសនា
              </a>
            </li>
          </ul>
          <div className="text-white flex justify-center mt-5">
            © 2024. All Rights Reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
